//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_lab12.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        public int id_customer { get; set; }
        public string surname_customer { get; set; }
        public string name_customer { get; set; }
        public string patronymic_customer { get; set; }
        public string telephone_customer { get; set; }
        public string email_customer { get; set; }
    }
}
